### PR TITLE
see yourself on your connections' connection list 

### PR DESCRIPTION
**Pull request by LeratoKgomo**
- the problem wasnt in the code it was just the database we might have to clean up everything and make requests and accept/reject requests via the app .. i cant really do that at the moment because i dont have every users login details so i have to do it manually 
- i also just sorted the connects list and made sure 'you' the logged in user is always at the top

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Ohhh @LeratoKgomo I know what happened, on the connection page, I did not realize that not the whole page will be filled with connection profiles, you have to scroll in the small container to see more connections, could you maybe make that container bigger ? 😅 Sorry that was my mistake

**Review by pieryvdl — COMMENTED** [review]
It works on my side too, thanks Lerato. Could you please also have a look at the connections page so that we can see all the connections on the page. 😄 The rest looks good. Thank you. 😊

**Comment by LeratoKgomo** [comment]
> Ohhh @LeratoKgomo I know what happened, on the connection page, I did not realize that not the whole page will be filled with connection profiles, you have to scroll in the small container to see more connections, could you maybe make that container bigger ? 😅 Sorry that was my mistake

@MonikaTheiss  and @pieryvdl you should now be able to see the whole list

**Review by MonikaTheiss — APPROVED** [review]
Awesome! Thank you @LeratoKgomo

**Review by pieryvdl — APPROVED** [review]
Thanks Lerato! Works on my side as well.

**Pull request merged**
