### PR TITLE
Caching for tags and genres

### PR DESCRIPTION
**Pull request by u22520016**
I added caching for genres and tags that get fetched from the API as well.

In some files it might look like there are a lot of changes, but that is just because I reformatted the code

### CODE REVIEW

**Review by MonikaTheiss — APPROVED** [review]
Works on my side, thank you!

**Comment by MonikaTheiss** [comment]
@u22520016 I don't know if you saw, but you have a conflict on this branch. Assume it happened due to another pull request merging before yours

**Review by LeratoKgomo — APPROVED** [review]

**Comment by u22520016** [comment]
Please review again I had to resolve the merge conflicts

**Comment by MonikaTheiss** [comment]
> Please review again I had to resolve the merge conflicts

@u22520016 I would love to review, but Github actions have failed. Could you perhaps fix it? Then I will approve 👍

**Review by MonikaTheiss — APPROVED** [review]
Looks good, thank you !

**Pull request merged**
