### PR TITLE
Feat/badges frontend

### PR DESCRIPTION
**Pull request by u22520016**
I integrated the badge page's frontend with the badges' backend.  I implemented the lock/unlock functionality and it now shows the correct date of when a badge was unlocked.  

I still need to implement a way for users to see other users' badges and also show the correct images of the friends who also have the specific badge on the particular badge page.  I also need to implement the description as soon as @pieryvdl helps me implement the description field for the database when a new profile is created.

### CODE REVIEW

**Review by MonikaTheiss — APPROVED** [review]
Looks good on my side, thanks

**Review by MonikaTheiss — APPROVED** [review]

**Comment by pieryvdl** [comment]
I fixed the dates on the creation of profiles so that Franco's code does not break. 

@shan-226 @LeratoKgomo If you could review please, I now also worked on the code and cannot review my own code.

**Review by MonikaTheiss — APPROVED** [review]

**Comment by LeratoKgomo** [comment]
i cant see the 3d badges  but everything else looks good

**Review by shan-226 — APPROVED** [review]
Looks good on my side.

**Pull request merged**
