### PR TITLE
Feat/update edit event page

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Edit event is now supposed to look like the create event page (hopefully). please let me know if I missed something

### CODE REVIEW

**Review by shan-226 — CHANGES_REQUESTED** [review]
Frontend looks good. Could you perhaps edit the choose game button to have a check icon as a game was already chosen when you created the event. It is currently the original plus icon.
When I click on the choose game button to edit the game, I get the same error I got in @pieryvdl pull request and can't access that page anymore.

**Comment by MonikaTheiss** [comment]
> Frontend looks good. Could you perhaps edit the choose game button to have a check icon as a game was already chosen when you created the event. It is currently the original plus icon. When I click on the choose game button to edit the game, I get the same error I got in @pieryvdl pull request and can't access that page anymore.

I'm sorry , I don't know why you get that error, it works on my phone and it also works on my web version....

**Review by pieryvdl — APPROVED** [review]
Thank you Monika! It works now and looks like the normal create events.

**Review by shan-226 — APPROVED** [review]
Looks good, thank you.

**Pull request merged**
