### PR TITLE
Feat/search friends

### PR DESCRIPTION
**Pull request by LeratoKgomo**
At the moment should be able to search for friends but the pending(friend request) and accepting friend request and undoing the friend request will give an error message in your terminal. That is because of the firebase permissions im trying to fix. This to get some of the code to develop

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
@LeratoKgomo I see there are a few merge conflicts. Do you want me to help you resolve them?

**Comment by LeratoKgomo** [comment]
im resolving them at the moment thank you

**Comment by MonikaTheiss** [comment]
goodluck!

**Comment by LeratoKgomo** [comment]
@MonikaTheiss  im actually a bit unsure how to resolve the conflicts in the home page i basically added another button to get to the search friends ... for now it should be there with the feed

**Pull request closed without merging**
