### PR TITLE
Wishlist service

### PR DESCRIPTION
**Pull request by MonikaTheiss**
I added a wishlist service which gets the user's wishlist, adds a game ID to the wishlist and removes a game ID from wishlist.
I also removed my profile management page , it is not needed at the moment

### CODE REVIEW

**Comment by pieryvdl** [comment]
Hi Monika, I ran the branch.  Codewise it looks good, although I couldn't really test it yet? Because there is no way to see if the game is being added.  Or maybe I missed how to add something to your wishlist. I trust that it works? 😄

**Comment by MonikaTheiss** [comment]
@pieryvdl yes, I tested it on my test API calls branch. If  you want I can commit that code and then you can try it out there? That's the way I tested it

**Comment by pieryvdl** [comment]
@MonikaTheiss Hi, yes please. That would help a lot, please just tell me how to get to it. 😊

**Comment by MonikaTheiss** [comment]
ok will do 👍

**Comment by MonikaTheiss** [comment]
@pieryvdl so under the test api calls branch, look on the home page , there is a function that has all the function calls for the wishlist. Just uncomment/ comment out things that you dont need

**Comment by MonikaTheiss** [comment]
Also sorry I forgot the actions run, I just made a small change I forgot, just changed the int to String , as the wishlist array is Strings

**Comment by pieryvdl** [comment]
Awesome, thanks i'll hop onto it in a second.

**Review by pieryvdl — APPROVED** [review]
Tested code. Seems to be working correctly. Thanks for your assistance @MonikaTheiss

**Review by shan-226 — APPROVED** [review]

**Review by pieryvdl — APPROVED** [review]

**Pull request merged**
