### PR TITLE
Feat/repo enhancement

### PR DESCRIPTION
**Pull request by pieryvdl**
Hi guys, added some more badges for us and made 2 new levels. I think there is an issue with level 5, but I will fix it, or create a new level.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Looks good, could you perhaps just put the flags back up top for level 1-4 please ? And then yes I see something weird going on with level 5 , I just die on a specific place if I jump and not too sure why that is.

**Comment by MonikaTheiss** [comment]
> Looks good, could you perhaps just put the flags back up top for level 1-4 please ? And then yes I see something weird going on with level 5 , I just die on a specific place if I jump and not too sure why that is.

I think the saws dont show up for some reason?

**Comment by MonikaTheiss** [comment]
sent a message to you about level 5

**Comment by pieryvdl** [comment]
Hi guys, I fixed the levels and I added credits for rawg on the specific game page. Please just check that it does not create overflows.

**Review by MonikaTheiss — APPROVED** [review]
Thank you so much for adding the credits and levels ! looks good on my side

**Review by shan-226 — APPROVED** [review]

**Pull request merged**
