### PR TITLE
Feat/more testing into develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Added multiple test skeletons and testing of existing pages. It was difficult to test some pages as they are not final yet and this would later on render the tests unusable.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
🥳 🥳 🥳  you got the coverage to go up by 16%! Thank you for the hard work you put into this! I will look into this once I have finished the MATLAB course

**Comment by LeratoKgomo** [comment]
this is amazing actually theres progress. Thank you!!

**Comment by LeratoKgomo** [comment]
not sure if its just on my side but i cant see the friends in the profile page

**Comment by pieryvdl** [comment]
Just double check that you have friends in Firebase. Mine is loading on my side. 
image

**Review by MonikaTheiss — APPROVED** [review]
Looks good! 
A small thing , I removed the profile management page , because its not necessary at the moment. I dont know if you want to remove it from your side? or do we just leave it as is?

**Comment by pieryvdl** [comment]
If we can remove it, then lets take it away... can you remove it from my branch and then merge this in? Or is it just the profile management page that I can take away?

**Comment by pieryvdl** [comment]
Removed successfully.

**Review by MonikaTheiss — APPROVED** [review]

**Pull request merged**
