### PR TITLE
Feat/games consistency

### PR DESCRIPTION
**Pull request by shan-226**
Made 3 games' frontend more consistent:
1. Made back button the same on all games
2. Changed font of scores
3. Changed alignment of scores
4. Made loading page for GameyCon scrollable - It was overflowing on my end
5. Added start page for Space Shooter

### CODE REVIEW

**Review by MonikaTheiss — COMMENTED** [review]
@shan-226 I ran it on my side, it looks good. Could you perhaps quickly take a look at the flappy bird game's back button. It looks different from the rest , I assume this is because Lerato added a button and with the merges it somehow got overwritten. 
Oh  and then I found a widget error in my console ,I am not currently sure how to recreate it, but it has happened on my phone and web version now, so it is something we need to fix. Otherwise the games will not show up on the release apk ( widget errors are why we get grey blocks in the release apks) Please also take a look at this. I currently cannot say why its happening, it will need a bit of debugging to figure out.

**Review by pieryvdl — COMMENTED** [review]
Hi Shannon, I looked at it now, maybe if you can resolve the error Monika was talking about, but the rest looks great thank you.

**Comment by u22520016** [comment]
I noticed some stuff:

1. The flappy bird back button is primary color while the rest are grey
2. I got the following error on the flappy bird page
Screenshot 2024-09-27 at 18 46 59
4. I got this error when trying to start the GameyCon game (I am testing it on web, so maybe that could also be the problem)
Screenshot 2024-09-27 at 18 47 57


The rest looks good though, thanks.

**Comment by MonikaTheiss** [comment]
@shan-226 thanks for changing the buttons ! I figured out where the widget error is being thrown, its when you start playing the space shooter game.

**Review by MonikaTheiss — APPROVED** [review]
Works on my side, thanks !!

**Review by pieryvdl — APPROVED** [review]
Thanks Shannon! Looks good on my side, in the future I think it would be cool if we changed Flappy bird to also be green, like Space Shooter and GameyCon, rest is great thanks!

**Pull request merged**
