### PR TITLE
Fix game library filter

### PR DESCRIPTION
**Pull request by u22520016**
I fixed the filtering for the game library page

Here are the main stuff I fixed:
1. I moved the clear filters button to the filter page
2. I added a Metacritic rating filter that uses a ranged slider with values 1-100
3. I added a way for users to see the currently active filters they have applied when they have filters applied (I'm not certain how I feel about the styling but let me know)
4. I fixed games loading that don't fit the filter criteria after scrolling
5. I fixed the scrolling issues within the filter page so that a user can now scroll even if a filter menu is expanded

I apologize for the time it took to make these changes.  But the code is quite complicated for the filter page😅

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
Hi Franco, code looks quite good, thank you for your hard work regarding the filters. Only thing would change is the text color of the filter to tertiary, so that it is black in both light and dark mode. Everything else looks good.

**Comment by MonikaTheiss** [comment]
It looks great on my side !! Thank you for putting in so much effort!
Maybe a one last thing I would want to do is perhaps when selecting a filter from a specific category, show the amount of filters selected, kind of what I did for the invite connections on the create event. If this is too difficult, then we can leave it .. let me know what you think?

**Comment by MonikaTheiss** [comment]
> It looks great on my side !! Thank you for putting in so much effort! Maybe a one last thing I would want to do is perhaps when selecting a filter from a specific category, show the amount of filters selected, kind of what I did for the invite connections on the create event. If this is too difficult, then we can leave it .. let me know what you think?

@u22520016  have you decided on this yet?

**Comment by u22520016** [comment]
> > It looks great on my side !! Thank you for putting in so much effort! Maybe a one last thing I would want to do is perhaps when selecting a filter from a specific category, show the amount of filters selected, kind of what I did for the invite connections on the create event. If this is too difficult, then we can leave it .. let me know what you think?
> 
> @u22520016 have you decided on this yet?

I think its a good idea I just need to figure out how IM going to show this

**Comment by u22520016** [comment]
I changed the Filter text color @pieryvdl and I added what you suggested @MonikaTheiss ... Please take a look😁

**Comment by shan-226** [comment]
It looks really good! I just have one comment. I changed the metacritic filter and applied it. It displayed correctly on the  search page. But when you go to the filter page again the metacritic slider does not reflect the previous filter which is still applied. It shows the entire range and not the one I previously selected. This is the same for all filters.
Then when you filter again it overwrites the current filters - I don't mind this but it maybe we should change it so that the user has to deselects the filters instead?

**Comment by u22520016** [comment]
> It looks really good! I just have one comment. I changed the metacritic filter and applied it. It displayed correctly on the search page. But when you go to the filter page again the metacritic slider does not reflect the previous filter which is still applied. It shows the entire range and not the one I previously selected. This is the same for all filters. Then when you filter again it overwrites the current filters - I don't mind this but maybe we should change it so that the user has to deselects the filters instead?

Yes, this is because the filter page reloads so the data on the filter page itself is also refreshed.  For this I will need to store the data globally somewhere and I can look into it, but for now I just want to merge the current changes in.

**Comment by MonikaTheiss** [comment]
> I changed the Filter text color @pieryvdl and I added what you suggested @MonikaTheiss ... Please take a look😁

Thank you! Looks good, will take a look at the code now

**Pull request merged**
