### PR TITLE
Feat/redesign customize page

### PR DESCRIPTION
**Pull request by LeratoKgomo**

### CODE REVIEW

**Review by shan-226 — CHANGES_REQUESTED** [review]
It looks good so far. Can you please update the themes container to be a bit bigger. Use the height on figma and then use padding above and below the icons and switch. And then it doesn't highlight/encircle the color theme that is currently selected, only when you click on the colored game controller does the circle/shadow appear for a second. 
When you click on the camera icon to change your profile picture, nothing happens. You have to click in the middle of the picture. @MonikaTheiss do you think this is fine, or should it be updated to be the camera icon only?

**Comment by LeratoKgomo** [comment]
@shan-226  i implemented the changes and then for the profile picture i spent alot of time on it but still couldnt figure out why i couldnt make the camera icon clickable  from the button right of the circle so i moved it to the center of the picture

**Comment by MonikaTheiss** [comment]
@LeratoKgomo thank you, it looks good! I have a bottom overflow by pixels on my side on the theme selector. Please look into that, when that is fixed, I will approve

**Comment by LeratoKgomo** [comment]
> @LeratoKgomo thank you, it looks good! I have a bottom overflow by pixels on my side on the theme selector. Please look into that, when that is fixed, I will approve

please double check if its fixed i also added the border that was suggested around the profile picture

**Comment by MonikaTheiss** [comment]
> > @LeratoKgomo thank you, it looks good! I have a bottom overflow by pixels on my side on the theme selector. Please look into that, when that is fixed, I will approve
> 
> please double check if its fixed i also added the border that was suggested around the profile picture

perfect, thank you that fixed the overflow !

**Review by MonikaTheiss — APPROVED** [review]
Thank you , I like it!

**Review by shan-226 — APPROVED** [review]
Perfect!

**Pull request merged**
