### PR TITLE
Feat/start timer

### PR DESCRIPTION
**Pull request by u22520016**
This code adds the interface for starting a timer when deciding to game.  It also includes the emotion rating when stopping the timer.  I also added a placeholder bar to show who of a user's friends are currently online.

### CODE REVIEW

**Comment by LeratoKgomo** [comment]
it looks great. I think the color change was a good idea and cant cause any misunderstanding. The emojis make it even more visually appealing so thank you for that 

So when i first tried to test i  didnt have games so it displays 'no data found' but i could still start the timer as though i had a game maybe in the future handle that type of case.
So with the emotions at the end of the timer we had decided on these 5 angry, fear, sad, joy and disgust 

when i do add games it works well im just wondering if in the future you will maybe display the game names or something similar instead of the IDs?

**Comment by pieryvdl** [comment]
Hi @u22520016 I can't find the timer to test it. Could you please direct on where to click to start the timer?

**Comment by u22520016** [comment]
> Hi @u22520016 I can't find the timer to test it. Could you please direct on where to click to start the timer?

You have to import the component into the feed page.  I didn't want to commit that change to the feed page since someone else worked on it and I didn't want to break any existing code.

**Comment by u22520016** [comment]
> it looks great. I think the color change was a good idea and cant cause any misunderstanding. The emojis make it even more visually appealing so thank you for that
> 
> So when i first tried to test i didnt have games so it displays 'no data found' but i could still start the timer as though i had a game maybe in the future handle that type of case. So with the emotions at the end of the timer we had decided on these 5 angry, fear, sad, joy and disgust
> 
> when i do add games it works well im just wondering if in the future you will maybe display the game names or something similar instead of the IDs?

I will handle this in the future, yes.

**Review by LeratoKgomo — APPROVED** [review]

**Review by pieryvdl — APPROVED** [review]
Seems to work as intended.

**Comment by MonikaTheiss** [comment]
> > it looks great. I think the color change was a good idea and cant cause any misunderstanding. The emojis make it even more visually appealing so thank you for that
> > So when i first tried to test i didnt have games so it displays 'no data found' but i could still start the timer as though i had a game maybe in the future handle that type of case. So with the emotions at the end of the timer we had decided on these 5 angry, fear, sad, joy and disgust
> > when i do add games it works well im just wondering if in the future you will maybe display the game names or something similar instead of the IDs?
> 
> I will handle this in the future, yes.

@u22520016 maybe you can so long create an issue for it, just so we don't forget about it?

**Pull request merged**
