### PR TITLE
Feat/redesign own profile2

### PR DESCRIPTION
**Pull request by LeratoKgomo**
should be able to see your **OWN** profile , i tried to get it as close to the figma design as possible

if you dont have games just copy and paste from my profile

### CODE REVIEW

**Review by u22520016 — COMMENTED** [review]
It looks so nice!  Thank you @LeratoKgomo.  Please just make sure the text in the "My Games" under the game's title is grey like in Figma.  Also just make sure the "View stats" button takes you to the stats page (I don't know if you can yet...if you can't then its fine)

**Comment by LeratoKgomo** [comment]
> It looks so nice! Thank you @LeratoKgomo. Please just make sure the text in the "My Games" under the game's title is grey like in Figma. Also just make sure the "View stats" button takes you to the stats page (I don't know if you can yet...if you can't then its fine)



it seems to be white in figma, and no i cant go to the stats page yet since it wasnt on my branch 

image

**Comment by LeratoKgomo** [comment]
> It looks so nice! Thank you @LeratoKgomo. Please just make sure the text in the "My Games" under the game's title is grey like in Figma. Also just make sure the "View stats" button takes you to the stats page (I don't know if you can yet...if you can't then its fine)

i changed this to grey

**Review by pieryvdl — APPROVED** [review]
Wow, Lerato this is absolutely brilliant! Thank you for your hard work! This looks excellent. Could you please change the settings  icon color to green? The rest is good with me.

**Review by u22520016 — APPROVED** [review]
It looks very good thank you.

**Pull request merged**
