### PR TITLE
Feat/selectgamepage into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Hey guys! 
You'll find:
1. The select a game when creating an event now looks like the one on figma. Please let me know if you encounter any issues, or see something off, but I'm pretty sure it should be fine. Let me know what you think! 
2. I also added the same _isMounted protection, I think it might come in handy to prevent the errors on the Feed Page or wherever we use setState.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
@pieryvdl what is supposed to happen when I click on a game?

**Comment by MonikaTheiss** [comment]
Also I believe @shan-226 might point this out too, but the padding underneath the "Select a game" AppBar  does not have the correct amount of padding , at least on my side.

**Comment by MonikaTheiss** [comment]
Also just a little fun fact , I see you pull request is number 404 😅 pretty cool

**Comment by shan-226** [comment]
The first time I ran the page and went to that page it worked. When I pushed the back button and then went to that page again an error displayed instead of the page. (White page, red words underlined in yellow: Error: ClientException: XMLHttpRequest errer., uri=https://rawg.api.io/api/games/58277?key=[our current api key] )  The key is the new one. Then i restarted the application and got that same error when I went to the page for the first time.  I don't always get this error, sometimes it works.
Some UI things: Please add padding beneath the app bar before the first game. When you click on the game nothing happens. Please add the radio buttons on the sides of the games like on figma to indicate that the game was selected. Then can you please add 10 rounding to the corners of the Save Game button.

**Comment by pieryvdl** [comment]
@shan-226 @MonikaTheiss Sorry, I should have double checked it seems I  forgot to make the setstate to in InitState, hence why nothing happened! Even though it was there, it just wasn't activated because setState was blocked. I added the padding, and rounded the button. Hope its good now.

**Comment by MonikaTheiss** [comment]
> @shan-226 @MonikaTheiss Sorry, I should have double checked it seems I forgot to make the setstate to in InitState, hence why nothing happened! Even though it was there, it just wasn't activated because setState was blocked. I added the padding, and rounded the button. Hope its good now.

thank you for fixing it! It looks great, will look at the code now and start my review 😄

**Review by MonikaTheiss — APPROVED** [review]
Code looks good! I'm happy , thank you.
Also thanks for adding the is mounted check !

**Comment by shan-226** [comment]
@pieryvdl It looks good. Sorry for only seeing this now and not including it in my initial comment. But the height of the button is too small. On figma it is 35. Can you please update it to 35?

**Comment by pieryvdl** [comment]
> @pieryvdl It looks good. Sorry for only seeing this now and not including it in my initial comment. But the height of the button is too small. On figma it is 35. Can you please update it to 35?

@shan-226 Done ✅

**Comment by pieryvdl** [comment]
> Also just a little fun fact , I see you pull request is number 404 😅 pretty cool

That's quite cool! I did not even notice!

**Review by shan-226 — APPROVED** [review]

**Pull request merged**
