### PR TITLE
Feat/readme

### PR DESCRIPTION
**Pull request by shan-226**
I added some technology badges to the readme.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Could you please make the pictures of us bigger , I see they are smaller than those on our main branch

**Comment by MonikaTheiss** [comment]
please close the pull request when making changes @shan-226 , so we dont use up all of our minutes

**Comment by shan-226** [comment]
Sorry, will remember that next time. I am done with the changes. Please review and let me know.

**Review by MonikaTheiss — APPROVED** [review]
Looks good , thank you!

**Comment by shan-226** [comment]
@pieryvdl can you please review this merge

**Review by pieryvdl — APPROVED** [review]
Looks great thanks!

**Pull request merged**
