### PR TITLE
Feat/cached network image functionality into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
This loads the images in our app, much much faster! Please check it out and let me know what you guys think. I have added the customCacheManager and then commented it out again because it resulted in an error. Another thing to note is that I don't know how this would affect Lerato's work on th customize banner. Hopefully it should not be an issue, but I am unable to test it since that code is not in Develop yet. let me know what you guys think? 😃

### CODE REVIEW

**Review by LeratoKgomo — APPROVED** [review]
definitely alot quicker . This will change some of the customize code but just please get this into develop then i can work from there.

**Comment by pieryvdl** [comment]
I added  an Image Provider. 2 benefits of this: 1. It provides more control over the image, 2. It seems to improve performance on web.

**Comment by pieryvdl** [comment]
Will reopen, I found a new bug.

**Comment by pieryvdl** [comment]
Emulator was at fault, code is fine.

**Review by MonikaTheiss — APPROVED** [review]

**Pull request merged**
