### PR TITLE
Feat/update invite connections

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Updated invite connections page to fit figma design. Warning: I do not know what it looks like on web , it might look weird, but it should look fine on emulator. @pieryvdl could you perhaps just add a screenshot of what the page looks like on your emulator, for those of us who can't use emulator please? Let me know if I need to change something 😊

### CODE REVIEW

**Review by shan-226 — APPROVED** [review]
It looks good!

**Comment by pieryvdl** [comment]
image
image
Hi Monika here is the screenshots.

**Comment by MonikaTheiss** [comment]
> image image Hi Monika here is the screenshots.

thank you! much appreciated 😄

**Review by pieryvdl — APPROVED** [review]
The code looks good. We can add Appbar, but the rest is great. Thanks Monika. I remember you said that @u22520016 has the search bar component, so I looked past that.

**Comment by MonikaTheiss** [comment]
Thank you for the reminder, I completely forgot about the appbar , I will add that later today.

**Comment by MonikaTheiss** [comment]
@pieryvdl I tried to add the appbar to the invite connections page, but the font size was too big and didn't look like the design.. did I do something wrong? Or can I leave it as is? what do you think?

**Comment by pieryvdl** [comment]
> @pieryvdl I tried to add the appbar to the invite connections page, but the font size was too big and didn't look like the design.. did I do something wrong? Or can I leave it as is? what do you think?

Hi Monika, I believe you can use it as is, if we do need to shrink the AppBar then we can always just edit the component.

**Comment by MonikaTheiss** [comment]
> > @pieryvdl I tried to add the appbar to the invite connections page, but the font size was too big and didn't look like the design.. did I do something wrong? Or can I leave it as is? what do you think?
> 
> Hi @MonikaTheiss , I believe you can use it as is, if we do need to shrink the AppBar then we can always just edit the component.

Alright will do

**Pull request merged**
