### PR TITLE
Fix/bugsandforgotpassword

### PR DESCRIPTION
**Pull request by pieryvdl**
Hey guys, some more fixes and features here:

1. Forgot password now works! You can test it by logging out and checking your email after you've sent a request.
2. Removed the duplicate Gaming session/tournament on the create event page
3. I added a label to the bottom of the stats pages to indicate that it is games
4. Added Android permissions asking when selecting images for the profile in customize profile. 
5. Wrapped the settings page in a scrollable widget. 

Let me know what you guys think!

### CODE REVIEW

**Review by MonikaTheiss — APPROVED** [review]
Well done ! Everything looks good on my side, thank you 😄

**Review by shan-226 — APPROVED** [review]
Looks good, reset password works!

**Comment by u22520016** [comment]
For some reason, I cannot run this specific branch on my device and don't know how to fix it...

Screenshot 2024-09-24 at 17 12 09

**Comment by pieryvdl** [comment]
@u22520016 try running "flutter clean" and then "flutter pub get" in your terminal and then running it a few times. It sometimes needs to clear the cache, before the code works. Not sure why, but it seems to work.

**Comment by u22520016** [comment]
> @u22520016 try running "flutter clean" and then "flutter pub get" in your terminal and then running it a few times. It sometimes needs to clear the cache, before the code works. Not sure why, but it seems to work.

I tried this but it still does not work.  I don't know what to do about it...

**Comment by pieryvdl** [comment]
Maybe try, "flutter upgrade" after you flutter pub get as there is a few new packages in the branch as well. I just ran the branch on my side again and it seems to be working, will have a look again and if there is something else I can fix.

**Comment by u22520016** [comment]
I did everything.  Nothing works...let's wait for Lerato to approve

**Comment by pieryvdl** [comment]
Cool.

**Comment by pieryvdl** [comment]
sdk.dir=C:\\Users\\piery\\AppData\\Local\\Android\\sdk
flutter.sdk=C:\\Users\\piery\\flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1

flutter.minSdkVersion=23
flutter.targetSdkVersion=34
flutter.compileSdkVersion=34 

@Franco please copy the above lines and put it inside android>local.properties ... This should make the branch run on your side, I completely forgot that that file is being ignored and explains why the branch is not working for you. Sorry this is my bad. Thank you to @MonikaTheiss for reminding me. 
Also @shan-226 and @LeratoKgomo you would need to do this too for it to work.

**Review by MonikaTheiss — APPROVED** [review]

**Pull request merged**
