### PR TITLE
adds image to event & displays events

### PR DESCRIPTION
**Pull request by MonikaTheiss**
You can now add images and a description to events. Then you can also click on events and subscribe to them ( the bell next to the event name) you can also join the event - note when oining the event there is no indication to the user that it was joined successfully yet. This is obviously not the final design

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Sorry for the amount of PR's I close and reopen, I was trying out something new, but then realised the check don't run

**Comment by MonikaTheiss** [comment]
@LeratoKgomo and @pieryvdl when you get the time can you have a look at this pull request please 😊 
I would like to get this in after Lerato's connection pull request , as she made a few changes to the connections card

**Review by LeratoKgomo — APPROVED** [review]
i couldnt change the image because my emulator doesnt work so i couldnt test that part but everything else works as intended. I like that it looks very clean theres quite a few information but the layout isnt overwhelming at all .At a later stage though i think we will have to change the  bell icon when the user subscribes maybe use one without the plus(+) so that there isnt any confusion.  So from my side im happy and thank you for the work you put in so far.

**Review by pieryvdl — APPROVED** [review]
The image can be changed successfully and the code works as intended. Thank you @MonikaTheiss! I could also subscribe like you mentioned.

**Pull request merged**
