### PR TITLE
Feat/game info page

### PR DESCRIPTION
**Pull request by shan-226**
I changed the favourite (heart) icon to a play button. I added the remove from my games and want to play functionality on the specific game info page. @MonikaTheiss and @LeratoKgomo please review when you can.

### CODE REVIEW

**Review by MonikaTheiss — CHANGES_REQUESTED** [review]
I am happy with the code and everything works as great, I like that the buttons change the text when you click on them, just a small thing I noticed. In the login file, on around line 228 , that scaffold message should be commented out, as that gives an error when its not supposed to give an error. In Develop it is commented out, I don't know why its not commented out on your side. Could you perhaps take that out please? Its not supposed to be in there.

**Comment by LeratoKgomo** [comment]
looks good
i noticed the 2 buttons for the want to play and my games are different, i think we should be consistent and have them the same ?

**Comment by MonikaTheiss** [comment]
Please wait for @u22520016 to answer my message on the group before merging. Thank you for the changes Shannon!

**Comment by u22520016** [comment]
I actually agree with @LeratoKgomo to keep the design the same for now...

**Comment by shan-226** [comment]
@u22520016  so the design is going to stay the same for now but will change in future? I just want to be sure.

**Comment by shan-226** [comment]
@LeratoKgomo and @MonikaTheiss please review this when Franco replies.

**Review by MonikaTheiss — APPROVED** [review]

**Review by MonikaTheiss — APPROVED** [review]

**Review by pieryvdl — APPROVED** [review]
Changes look good. We will have to rename some of the functions from the backend side, but they look good on the front end.

**Pull request merged**
