### PR TITLE
feat/logoRework into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
I fixed the app Icon and the appbars. 

1. The correct logo is now being used across the app. 
2. The Appbars now have the same styling on all the pages. 

@LeratoKgomo  Please just checkout the profile page, I thin the "live game" section might not be loading on my page? Can you please check it out, I think it should be rather easy to fix? 😄 
image

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
@pieryvdl  If you have the time, could we perhaps call the app bar on the view events page "events" or something along that line? As joined  events are only the top events

Then I know this is not an error from your side, but I noticed on the view events, there are now 2 subscribe (bell) buttons. I assume this happened with some merge somewhere. I won't be able to fix it tonight though.

**Comment by LeratoKgomo** [comment]
looks cleaner thank you , dont you think we should do the same for the edit profile and customize? 

with the currently playing it doesnt work because the code currently expects a game id and you provided the game name

**Review by MonikaTheiss — APPROVED** [review]
Looks great, thank you !  I'm also pretty happy to see the logo for GameOnConnect has been updated, now it looks very cool on my phone, thank you. I did leave a comment, but those are not big issues, so I won't mind if you decide to merge it in as is and later we can fix it all up

**Comment by pieryvdl** [comment]
> @pieryvdl If you have the time, could we perhaps call the app bar on the view events page "events" or something along that line? As joined events are only the top events
> 
> Then I know this is not an error from your side, but I noticed on the view events, there are now 2 subscribe (bell) buttons. I assume this happened with some merge somewhere. I won't be able to fix it tonight though.

Hi Monika, I changed it to 'Events' as requested. yeah I've got no idea how the double bell got there. It seems like there is two different bells on lines 134 and then again n line 156 of the specific_event.dart page.

**Comment by pieryvdl** [comment]
> looks cleaner thank you , dont you think we should do the same for the edit profile and customize?
> 
> with the currently playing it doesnt work because the code currently expects a game id and you provided the game name

Hi @LeratoKgomo i fixed it and added the styling to the edit and customize profiles as well. 

I'm really not sure what I mean by the currently playing. To my knowledge I don;t know where that is being provided. Could you direct me on how to fix it for tommorrow?

**Review by LeratoKgomo — APPROVED** [review]
looks great thank you 

i fixed your currently playing field in the database  so just try again and let me know if you still cant see it

**Comment by MonikaTheiss** [comment]
> > @pieryvdl If you have the time, could we perhaps call the app bar on the view events page "events" or something along that line? As joined events are only the top events
> > Then I know this is not an error from your side, but I noticed on the view events, there are now 2 subscribe (bell) buttons. I assume this happened with some merge somewhere. I won't be able to fix it tonight though.
> 
> Hi Monika, I changed it to 'Events' as requested. yeah I've got no idea how the double bell got there. It seems like there is two different bells on lines 134 and then again n line 156 of the specific_event.dart page.

I will try to fix this now

**Pull request merged**
