### PR TITLE
Feat/update view events

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Tried to get the view all events page to look like the design on figma.

### CODE REVIEW

**Review by shan-226 — CHANGES_REQUESTED** [review]
Upcoming Events Cards: 
1. Please add more padding to the left of the first card.
2. The width of the cards is a bit too long. Can you make it the width used on figma.
The All, Subscribed and My Events buttons:
1. Can you change their layout to be spaced evenly (the main axis alignment of the row).
The events below the buttons: 
1. Can you make the left/right padding be a little less and to match the alignment of the above first upcoming event card. 
Use 15 padding on the sides for all components.

It looks really good so far.

**Review by pieryvdl — CHANGES_REQUESTED** [review]
I agree with Shannon's suggested changes, the only thing I would add is that the rounding of the buttons is a tiny bit more on Figma. 

But it really looks great Monika! The main changes are there.

**Comment by MonikaTheiss** [comment]
I have updated the view events page. However I am waiting on a few of my questions to be answered on discord before I decide this is final. Closing this until I have answers

**Review by pieryvdl — APPROVED** [review]
I'm happy, the code looks good and works as intended thank you Monika!

**Pull request merged**
