### PR TITLE
Feat/edit profile design

### PR DESCRIPTION
**Pull request by shan-226**
I updated the edit profile page to look like the figma design.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
ok small weird thing when I tried to edit my profile .. I tried to change my birthday date and when I selected a date , the date I selected didn't update on the page itself. It did save it correctly on firebase, but this was a bit confusing at the start. Could you perhaps look into that? I

**Comment by pieryvdl** [comment]
Hi Shannon, most of the page looks good, but the switch color when activated is weird. Could you perhaps change it, you can look at the component made I for the themes, it is called the activeThumbColor I think. Then also the date issue that @MonikaTheiss described, but the design has '/' where the '-' is used on the branch.

**Comment by shan-226** [comment]
I fixed the calender issue and the switch coloring. @MonikaTheiss and @pieryvdl can you please review when you get the chance.

**Review by pieryvdl — APPROVED** [review]
Hi Shannon, thank you changes look good!

**Review by MonikaTheiss — CHANGES_REQUESTED** [review]
Small thing I noticed : the save changes text color is supposed to be black on both light and dark mode, according to the design on figma. The rest looks good, thank you. When you change the font color please let me know so I can approve the pull request !

**Comment by shan-226** [comment]
> Small thing I noticed : the save changes text color is supposed to be black on both light and dark mode, according to the design on figma. The rest looks good, thank you. When you change the font color please let me know so I can approve the pull request !

Done

**Review by MonikaTheiss — APPROVED** [review]

**Pull request merged**
