### PR TITLE
Feat/messaging implementation into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Hey guys, here is the messaging service in its current state. I know it looks a bit wonky on the messaging page, I will still fix that, but for now this is what i got working with the chats. You should be able to create a chat with all the users listed, I will refine this later. I used the functions @shan-226  wrote and added some as well that were needed. Hope you guys like it.

### CODE REVIEW

**Comment by LeratoKgomo** [comment]
it works as intended i also saw you connected the message in the connections page ...Im not sure if its possible at the moment or if you will only be able to do it later but can you connect it to the specific conversation page so if i from the connections i click on message bytesquad can you actually link to the bytesquad conversation not like the whole list of possible conversations. The images arent loading im not sure how you are getting them but theres a storage service that can get the images for you directly from storage just provide the uid of the user.

**Comment by MonikaTheiss** [comment]
@pieryvdl I tried sending messages to other profiles, but none of them worked, the messaging only works on your chat? Do you perhaps know why that is?

**Comment by pieryvdl** [comment]
I'm not sure. Will check it out and fix it. Thanks for letting me know.

**Comment by pieryvdl** [comment]
@MonikaTheiss I am unsure why it did not work for you. Could you please show me what happens in tomorrow's standup? I checked the messages again now and it seems to be working on my side. 

@LeratoKgomo Hi Lerato, yes I can add that for you as well. It wouldn't be too difficult. I will also fix the profile images not loading, I wanted to get this onto Develop and then I will use the storage service. As for the directly going to a chat, it is easy to add, I will add it for you when I get this into Develop.

**Comment by MonikaTheiss** [comment]
I started testing it out, I got this error when I sent a message to mike11@@ , ShadowPrincess, francotest , don't know of the rest.
image

Interesting enough, when I close the chat and open it again it does load my messages. I can try to show you later on.

**Comment by pieryvdl** [comment]
Okay cool. Thanks for showing me, it is the scrolling that is not working, because there aren't any messages found. Will try to fix it.

**Comment by MonikaTheiss** [comment]
we can merge it in for now, if its only those smaller issues

**Review by MonikaTheiss — APPROVED** [review]

**Review by LeratoKgomo — APPROVED** [review]

**Pull request merged**
