### PR TITLE
Feat/asset update

### PR DESCRIPTION
**Pull request by LeratoKgomo**

### CODE REVIEW

**Review by shan-226 — APPROVED** [review]
Looks amazing!

**Review by MonikaTheiss — APPROVED** [review]
Looks good ! Thank you for taking the time to change it up a bit !

**Review by u22520016 — APPROVED** [review]
It looks really good!  Thank you!  I would just suggest changing the bird as well to something else.  I can help design something if you want.  I would also then suggest changing the name of the game to something else (as we discussed).  If we change the bird to something else, we should just remember to change the icon of the game on the games page as well.

**Comment by LeratoKgomo** [comment]
> It looks really good! Thank you! I would just suggest changing the bird as well to something else. I can help design something if you want. I would also then suggest changing the name of the game to something else (as we discussed). If we change the bird to something else, we should just remember to change the icon of the game on the games page as well.

yes please if you can help design that please do

**Pull request merged**
