### PR TITLE
view specific event updated front-end to fit figma design

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Made the view specific event page look like the figma design. Warning: I do not know what it looks like on web , it might look weird, but it should look fine on emulator. @pieryvdl could you perhaps just add a screenshot of what the page looks like on your emulator, for those of us who can't use emulator please? Let me know if I need to change something 😊

### CODE REVIEW

**Comment by pieryvdl** [comment]
image
Hi Monika, unfortunately there is something wrong. 

E/flutter ( 6958): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'allEvents' has not been initialized.
E/flutter ( 6958): #0      _HomePageWidgetState.allEvents (package:gameonconnect/view/pages/events/view_events_page.dart)
E/flutter ( 6958): #1      _HomePageWidgetState.getAllEvents (package:gameonconnect/view/pages/events/view_events_page.dart:41:46)
E/flutter ( 6958): #2      _HomePageWidgetState.initState (package:gameonconnect/view/pages/events/view_events_page.dart:32:5)
 I get this in the terminal.

**Comment by MonikaTheiss** [comment]
> image Hi Monika, unfortunately there is something wrong.
> 
> E/flutter ( 6958): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'allEvents' has not been initialized. E/flutter ( 6958): #0 _HomePageWidgetState.allEvents (package:gameonconnect/view/pages/events/view_events_page.dart) E/flutter ( 6958): #1 _HomePageWidgetState.getAllEvents (package:gameonconnect/view/pages/events/view_events_page.dart:41:46) E/flutter ( 6958): #2 _HomePageWidgetState.initState (package:gameonconnect/view/pages/events/view_events_page.dart:32:5) I get this in the terminal.

Sorry my fault, try again please. This happened because I created an event and there wasnt a creatorName found in the event

**Comment by MonikaTheiss** [comment]
actually @pieryvdl now that you found that error, could you maybe try the to create an event please? I believe I created the event on an old branch, but I'm not too sure and we need to make sure the creator name is added to the database

**Comment by MonikaTheiss** [comment]
(the late initialization error occurs because of the stream I believe, not too sure how to fix it for now, but it works even with the late initialization error) The error screen you got was because of the event I created

**Review by pieryvdl — CHANGES_REQUESTED** [review]
Hi Monika, the changes look great! Here is a tournament I created. 
The only thing I want to point out is the padding under the image and the tournament name seems to be too little. And the tournament image seems overwhelmingly large compared to figma. 
image

**Comment by MonikaTheiss** [comment]
@pieryvdl thank you for catching that

**Review by pieryvdl — APPROVED** [review]
Looks great. thanks Monika!

**Comment by MonikaTheiss** [comment]
@u22520016 please review this when you get the time

**Review by u22520016 — APPROVED** [review]
Works :)

**Review by pieryvdl — APPROVED** [review]

**Pull request merged**
