### PR TITLE
Feat/connections profile redesign

### PR DESCRIPTION
**Pull request by LeratoKgomo**
should be able to see other users profiles whether they are your connections or not and whether they are public or private 

Note the view stats hasnt been linked yet so you cant view the stats at the moment

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
How do I access someone who is not my connection's profile? I tried in the search page, but that didnt work

**Comment by u22520016** [comment]
It looks very good thanks!  I just noticed that every single profile is currently online.  We might need to change it to "Currently playing" to show that a user is currently playing a game, since that was the original purpose of it.  And then this should only be displayed when a user's currently playing field is set to some sort of game (meaning that they have started a timer).

**Comment by LeratoKgomo** [comment]
> How do I access someone who is not my connection's profile? I tried in the search page, but that didnt work

this should be fixed now

**Comment by LeratoKgomo** [comment]
> It looks very good thanks! I just noticed that every single profile is currently online. We might need to change it to "Currently playing" to show that a user is currently playing a game, since that was the original purpose of it. And then this should only be displayed when a user's currently playing field is set to some sort of game (meaning that they have started a timer).

i changed this as well i display the currently playing if theres data in the field

**Review by MonikaTheiss — APPROVED** [review]
Looks good, thank you @LeratoKgomo for adding my suggestion! I'm happy with this 😊

**Review by u22520016 — APPROVED** [review]
Looks good and everything seems to be working.  Thank you.

**Pull request merged**
