### PR TITLE
Feat/help menu

### PR DESCRIPTION
**Pull request by MonikaTheiss**
I fixed the login bug , when an invalid user's details are entered, the username and password fields empty and a snackbar warning pops up. I also changed the signup page to look like the wireframe. I also added a slide menu on the profile for the settings , help menu and logout option. The help menu is still a work in progress , I just wanted to get these changes on Develop for now.

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
Looks awesome!

**Comment by pieryvdl** [comment]
I can help with the merge conflicts if you like.

**Review by pieryvdl — APPROVED** [review]

**Comment by MonikaTheiss** [comment]
@LeratoKgomo could you ,when you get the time, please review this 😊 ?

**Comment by LeratoKgomo** [comment]
The snackbar pop up works , the signup looks great! The slide menu works i just have a few suggestions for the design for now its not that important by i think later when we get time we can look imto these:

1. would it not be possible to have a settings page instead of a slide menu ... in most apps ive seen usually the settings has its own page 
2. would it be possible to change the font size of the settings heading just so it differs from the rest of the fonts in the list 
3. I see you added a divider not sure if its just on my side but its a bit low  if you either maybe remove it or move it a bit higher 

i love the green buttons in the help Centre looks really good , thank you

**Comment by MonikaTheiss** [comment]
Thank you for the feedback @LeratoKgomo 😃 for the settings page - we can do that, I just did the sliding menu do it because I didnt have a design to look at , so I just went with that. But I can change it. I'll change the fontsize - I wasn't sure if we wanted to have it say settings at the top. But I can change it. And lastly if you mean the divider on signup, I can move it up , no problem 👍 
Will let you know when I have made those changes for you to review again 😎

**Pull request closed without merging**
