### PR TITLE
Feat/profile firebase integration into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Loaded Firebase Information into Profile page and created tabs. In the future we might need to move the tabs. Please run the branch and make sure you are happy with it. Also notice I changed the app Icon and the App Name. Thanks in Advance!

### CODE REVIEW

**Comment by pieryvdl** [comment]
The reason for the many files changed is the icons that were dynamically loaded.

**Review by MonikaTheiss — APPROVED** [review]
I saw the icon - It looks great ! I'm happy thank you !

**Comment by pieryvdl** [comment]
> I saw the icon - It looks great ! I'm happy thank you !

Also thanks for your help!

**Review by shan-226 — APPROVED** [review]

**Comment by LeratoKgomo** [comment]
@pieryvdl im not sure if its just me but when i get to the profile page it says no profile data found

**Comment by pieryvdl** [comment]
@LeratoKgomo With what account are you logging in? Because some of the accounts don't have all the profile data. The bytesquad.capstone@gmail.com does not have an image, name or username... so it could be that?

**Comment by LeratoKgomo** [comment]
@pieryvdl its definitely that cause i used that account ... which account has data

**Comment by pieryvdl** [comment]
Check discord, Monika's account has data.

**Comment by LeratoKgomo** [comment]
@pieryvdl everything looks great placing the taps at the top is definitely a good idea , the divider could be a bit higher i think theres too much space between the username and the divider, but this isnt a major issue. Lastly it may just be on my side im not sure but in the games tab there this yellow and black rectangle at the bottom

**Review by MonikaTheiss — APPROVED** [review]

**Pull request merged**
