### PR TITLE
Feat/update create events

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Tried to get the frontend to look like the designs on figma. This is only for the create events page, not for the invite/choose game pages

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
I forgot the little camera icon

**Review by shan-226 — DISMISSED** [review]
It looks really good so far. There are just a couple of small fixes that need to be done. The circle on the picture beneath the camera icon should be light grey and somewhat tranparent. The 0/50 beneath the even name's spacing is incorrect, it needs to be closer to the event name text box than the choose game one. The same with the 0/100 one for the description. The alignment of the game session and tournament buttons is off, can you make them longer and in the middle/take up the entire length like on figma. Can you also move the private switch to be at the end of the grey container around it.

**Comment by MonikaTheiss** [comment]
Thank you for your feedback @shan-226 , unfortunately I have some bad news.. I spoke to Franco today and he said the camer's circle should be primary container color, which it currently is, so we decided we won't change that. I have however made it a bit transparent, hopefully that makes it look lighter too. The word counters I cannot move, it is not my code that does that, the counter is automatically added when I use the maxlength attribute in flutter. I tried moving the provate switch to the end, this is the furthest I could move it before it gives an overflow error on my side. And then for the option chips, I did try to get it centered and this is the best I can do .. on my side it looks fine, but I will quickly run it on web so I can see if it looks different on web.

**Comment by MonikaTheiss** [comment]
This is the best I could get for the create events page

**Review by shan-226 — CHANGES_REQUESTED** [review]
Thank you for making the change for the circle around the camera icon it looks perfect. The picture seems to have gotten narrower and doesn't match the length of the rest of the components on the page.  Could you make the Gaming Session and Tournament buttons the same length? Those buttons are currently against each other and left aligned, would it be possible to add some padding between them and center aligning them even if they are not the full lengths? The label Private is no longer aligned with the labels above it. If you can't do these things just let me know and I will approve the pull request.

**Review by shan-226 — APPROVED** [review]
Looks good! Thank you! Just remember to update the choose a game and invite connections pages to look like on figma.

**Review by pieryvdl — APPROVED** [review]
Changes look good to me! Thank you Monika. I think the Private not being aligned to the Select a Data is super marginal (ie too small to notice immediately). I think there are more pressing issues to attend to. We should make a mental note: I think when an event has been created successfully to move over to the view events page, because it feels weird creating an event and then not being moved to the view_events page. But not something major now. Thank you for the work.

**Comment by MonikaTheiss** [comment]
> Changes look good to me! Thank you Monika. I think the Private not being aligned to the Select a Data is super marginal (ie too small to notice immediately). I think there are more pressing issues to attend to. We should make a mental note: I think when an event has been created successfully to move over to the view events page, because it feels weird creating an event and then not being moved to the view_events page. But not something major now. Thank you for the work.

I tried and failed 😅  moving the user over to another page is difficult without using push

**Pull request merged**
