### PR TITLE
Feat/view events

### PR DESCRIPTION
**Pull request by MonikaTheiss**
You can now view all events on the events page.

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
Code looks great Monika. Thank you! 2 things I noticed, we might need to give user feedback that an event was created and prevent them from duplicating the event, or atleast clearing the event when made. It does however correctly create an event and display it. Still a tiny issue with the time as described in previous pull request. Overall super happy, it looks great Monika! Thank you.

**Comment by MonikaTheiss** [comment]
> Code looks great Monika. Thank you! 2 things I noticed, we might need to give user feedback that an event was created and prevent them from duplicating the event, or atleast clearing the event when made. It does however correctly create an event and display it. Still a tiny issue with the time as described in previous pull request. Overall super happy, it looks great Monika! Thank you.

Thank you! Not to worry, this is not the final version, I will still work on all of that , I just jump between create event and view event branches when I'm waiting for a pull request to be approved, so I don't have to sit around and wait for it to be approved before I can continue working on stuff.

**Review by LeratoKgomo — APPROVED** [review]
works as intended , looks really good as well. Code wise you really did modularize very well. From my side im happy.Thank you

**Comment by pieryvdl** [comment]
Okay cool. I'm almost done with setting a username after signup via google there is a tiny bug. Will commit tonight and then focus on the messaging system.

**Comment by MonikaTheiss** [comment]
> Okay cool. I'm almost done with setting a username after signup via google there is a tiny bug. Will commit tonight and then focus on the messaging system.

perfect ! Thank you 😄

**Pull request merged**
