### PR TITLE
Fix/overflows

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Tried to fix all the overflow errors Shannon showed on the error reporting channel. 
Note: the game library does still have an overflow, but that will be fixed with Franco's front end fixes he wants to merge in. @shan-226 please run this on your phone and let me know of any other overflow errors you find 😊 
@pieryvdl perhaps if you could run the branch on a web phone with a width of 320 , and let me know if you find any other overflows. 
I didn't want to change all pages, as that will take a long time, so if you see something , please let me know, so I can change it.

### CODE REVIEW

**Comment by pieryvdl** [comment]
image
image
image
image


Hi Monika, so I found overflows here and on the stats page. But i think the search page will be fixed when we merge in Franco's changes to remove the reviews, so I don't think this will be an issue. 

Rest of the pages seem all good! Thank you for you hard work on this! It helps a lot. You are doing great work.

**Review by pieryvdl — CHANGES_REQUESTED** [review]
As mentioned above.

**Comment by MonikaTheiss** [comment]
> As mentioned above.

Stats page I will fix, thank you for pointing it out. The game library will be fixed in Franco's pull request so it should be fine. Then on the timer, could you  perhaps make sure that you have the newest code, it should not give an overflow error there, and I dont get that overflow error on my side. 
Thank you for responding so quickly !

**Comment by pieryvdl** [comment]
Hi Monika, just tested it again, there is an overflow there unfortunately.
image

**Comment by MonikaTheiss** [comment]
> Hi Monika, just tested it again, there is an overflow there unfortunately. image

how is that possible ... I used the exat values you used for the width and height and I don't get an overflow .. weird.

**Comment by pieryvdl** [comment]
Not sure, but definitely a weird issue. I suppose it could just be on my browser specifically? I think if it is not on @shan-226 phone then it should be fine?

**Comment by MonikaTheiss** [comment]
> Not sure, but definitely a weird issue. I suppose it could just be on my browser specifically? I think if it is not on @shan-226 phone then it should be fine?

Will try to take a look at it again... It should not be a browser issue .. but will check it again

**Comment by shan-226** [comment]
I ran it on my phone and the only overflows I get are on the search page and on the events page. The subscribed and my events buttons overflow. I sent a photo to you over whatsapp.

**Pull request closed without merging**
