### PR TITLE
Fix/messaging bug fix1 into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Hey guys here is what I fixed. 

1. The profile images now create with the correct links to the actual images as stored in Storage. 
2. Fixed being able to send empty messages.
3. Fixed sending new messages to accounts, will now send immediately send you send from the connections page if you have not sent the messages before. 
4. There is now feedback on the messages page that no chats were found.

### CODE REVIEW

**Comment by LeratoKgomo** [comment]
im not sure if its just on my side but the messages page has just been loading for a few minutes without displaying anything

**Comment by pieryvdl** [comment]
> im not sure if its just on my side but the messages page has just been loading for a few minutes without displaying anything

@LeratoKgomo It could be due to an account not existing. I'll send a message on WhatsApp.

**Review by MonikaTheiss — APPROVED** [review]
It works! Thank you

**Review by shan-226 — APPROVED** [review]
It works as intended.

**Pull request merged**
