### PR TITLE
Feat/stream events page

### PR DESCRIPTION
**Pull request by MonikaTheiss**
The view events page now updates when you subscribe to an event/ join an event ( the stream is now working) I also changed the events a bit so that you will be able to see private events everywhere except on the all events tab

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
I created a tournament to see if the changes worked. It seemed to work and the tournament was there immediately, I just wanted to show the stream might not work as expected. but the data is correct. 
image
Please see the top of this page of the new tournament.

**Comment by MonikaTheiss** [comment]
> I created a tournament to see if the changes worked. It seemed to work and the tournament was there immediately, I just wanted to show the stream might not work as expected. but the data is correct. image Please see the top of this page of the new tournament.

Did you make this event private? I cant see it

**Comment by MonikaTheiss** [comment]
> image @MonikaTheiss If you look at the top of this tournament, not sure if you can see it. But you can merge this in for now. It seems like a small issue. I also made the tournament public for your viewing.

Is that not just the items on your top bar on the phone? If you want me to move the image down, I can do that, although I would rather wait for the design team to finish first.

**Review by pieryvdl — APPROVED** [review]
As you pointed out correctly today in class.The issue I saw was not actually an issue.

**Pull request merged**
