### PR TITLE
Feat/game info page

### PR DESCRIPTION
**Pull request by shan-226**
I fixed all the things you suggested. I am creating a new pull request because the previous one did not recognize any new changes I made. The gitGaurdian was uncovering secrets in code that no longer existed in the branch.

### CODE REVIEW

**Comment by shan-226** [comment]
The GitGuardian is alerting to the following 3 things. First secret: is old code, the code no longer looks like this. Second secret: Same problem, its old code that no longer looks like this. Third secret: it is alerting to the old version of the code not the new. I removed the api key, but GitGuardian is still alerting to the old code I think. @MonikaTheiss can you review this and let me know if the check can be skipped seeing as the api key is already removed from the code. I think it is a false positive to old code.

**Comment by pieryvdl** [comment]
Technically that API key should be added to the .ENV file and then be revoked,  because it is exposed. Which means anyone that can see this repo can abuse our API key. It should also be added as a secret and then everyone on our team should get the new .ENV file so that we can replace the code to protect the API Key. See the secrets in the firebase_options.dart file. The same way that the keys are protected is the same way that we need to protect the API key. Let me know if you need help and I will help to keep the key safe and reroll it.

**Comment by pieryvdl** [comment]
image
Unfortunately the game_details page also does not open on this branch, there is an error with the loading of the game screenshots as indicated by the image above. The code breaks on the fetchGameScreenshots() functions in the game_service.dart file. Hope this helps.

**Comment by pieryvdl** [comment]
Upon further inspection to the branch I realize that the API key was indeed changed to be 'RAWG_API_KEY' as indicated. Apologies for this oversight. Did you also add the secret as a repository secret? It is also important that the new .ENV file is shared with the rest of the group, because I think this is why the screenshots did not load as indicated above. The CI/CD .ENV file should also be updated to that it constructs that secret as well.

**Comment by MonikaTheiss** [comment]
@shan-226 I believe gitguardian scans all your commits as all your commits are merged into Dev, and so anyone who wants to can look through the different commits and then find the api key easily. This is why git guardian fails, you cannot fix it on this branch, it will always check through all your commits. Please follow @pieryvdl 's advice.

**Comment by shan-226** [comment]
I revoked the rawg api key and got a new one. It is in the .env file that I shared on discord. I also put the new key in our repository secrets. I skipped the GitGuardian as it is now only alerting to the old api key that is not being used anymore. @MonikaTheiss and @pieryvdl can you please review this pull request when you get the chance.

**Comment by MonikaTheiss** [comment]
Because you changed the api key things, the games don't load on the search page anymore. I did add the RAWG API key to my .env file but yeah I dont see any games that I can click on

**Review by MonikaTheiss — APPROVED** [review]
Looks good, thank you !

As I mentioned we will just in the future have to look at the overflow things

**Pull request merged**
