### PR TITLE
Feat/game library caching

### PR DESCRIPTION
**Pull request by u22520016**
This is an important PR.  I tagged everyone to review because I want everyone to look at the added code and the caching managers.

I believe what I added now should sort out the caching for the API as a whole (since only 2 functions are mainly used in the services to make API requests).  I do not know if there are other API requests directly on other pages, but please ensure you use the GameService functions to make API requests if you know of a page that you created that makes API requests in the page itself, rather than using the GameService to make the requests.

This PR should at least help in loading times overall and also help with the API request limit if used correctly.

Please also check that everything is working as it should and that the code looks fine.

### CODE REVIEW

**Review by pieryvdl — COMMENTED** [review]
Hi Franco, I looked at the code now. It sort of makes sense to me how you did it, but I just want to clarify. So the amount of pages you get, I see it is specified to 20, do you know if there is a limit on how many games we can get from the API in one go? 

Then I see you put max objects in the cachemanager as 100... would making it bigger slow down the app? 
Then a question about the cachemanager, I read in the package description that it is used as a singleton, I'm assuming when we create new cache managers for other files we should do it like that as well? 

Overall the performance on the games significantly improved. thank you very much for changing this it helps a ton. Good work!

**Comment by u22520016** [comment]
> Hi Franco, I looked at the code now. It sort of makes sense to me how you did it, but I just want to clarify. So the amount of pages you get, I see it is specified to 20, do you know if there is a limit on how many games we can get from the API in one go?
> 
> Then I see you put max objects in the cachemanager as 100... would making it bigger slow down the app? Then a question about the cachemanager, I read in the package description that it is used as a singleton, I'm assuming when we create new cache managers for other files we should do it like that as well?
> 
> Overall the performance on the games significantly improved. thank you very much for changing this it helps a ton. Good work!

I don't know if there is a specified limit for the amount of pages, but you can definitely increase the number to like 100 or something.

The cache manager max objects is there to limit the size of the cache...so I don't know if it will make the app slower, but it will definitely lead to a larger cache size (obviously).  We can experiment with this and see how it affects the app.

Yes the cache manager is singleton such that there arent multiple copies of the same data.  We should however create different cache managers for different TYPES of data though (like profile data, etc) to manage the cache seperately.

**Comment by pieryvdl** [comment]
> > Hi Franco, I looked at the code now. It sort of makes sense to me how you did it, but I just want to clarify. So the amount of pages you get, I see it is specified to 20, do you know if there is a limit on how many games we can get from the API in one go?
> > Then I see you put max objects in the cachemanager as 100... would making it bigger slow down the app? Then a question about the cachemanager, I read in the package description that it is used as a singleton, I'm assuming when we create new cache managers for other files we should do it like that as well?
> > Overall the performance on the games significantly improved. thank you very much for changing this it helps a ton. Good work!
> 
> I don't know if there is a specified limit for the amount of pages, but you can definitely increase the number to like 100 or something.
> 
> The cache manager max objects is there to limit the size of the cache...so I don't know if it will make the app slower, but it will definitely lead to a larger cache size (obviously). We can experiment with this and see how it affects the app.
> 
> Yes the cache manager is singleton such that there arent multiple copies of the same data. We should however create different cache managers for different TYPES of data though (like profile data, etc) to manage the cache seperately.

Okay cool. thanks for the answers Franco! The code and performance looks great on my side! I'm going to try and replicate what you did, I think it might differ a little bit for Firebase, but the games stuff looks great. Thanks man.

**Review by pieryvdl — APPROVED** [review]
Awesome changes!

**Review by MonikaTheiss — COMMENTED** [review]
Looks good, haven't tested it on my side yet. I think the one thing I would want to change is to load all this info when the user starts GameOnConnect, simply because if the user perhaps goes to their profile page first before going to the search page, the data should already be loaded, otherwise it will become very difficult for the code to be modular. We can discuss this tomottow though

**Review by MonikaTheiss — APPROVED** [review]
It does load quicker, thank you @u22520016 for figuring this out

**Pull request merged**
