### PR TITLE
Feat/customize functionality

### PR DESCRIPTION
**Pull request by LeratoKgomo**

### CODE REVIEW

**Comment by LeratoKgomo** [comment]
basically i added the functionality to add and remove tags and also update the database accordingly 
i dont wanna make a mistake with resolving  the conflicts  for the pubspec.lock conflict im not sure which one to 
and keep since i has to resolve both conflicts at the same time i also left out the conflict in the customize page but pls only keep whats from the customize branch and remove whats in the develop branch

**Comment by LeratoKgomo** [comment]
@MonikaTheiss can you also please review when you get the chance

**Review by MonikaTheiss — APPROVED** [review]
UI looks good & it updates in the database 🥳 Thank you @LeratoKgomo  for your hard work on this page !!!
We will have a look at the merge conflicts

**Comment by pieryvdl** [comment]
If you feel it is working @MonikaTheiss I think you can merge this in. I will only be able to have a look later today.

**Review by pieryvdl — APPROVED** [review]
From what I can see the code looks good.

**Comment by pieryvdl** [comment]
I would keep the higher version, yes. I'm unsure myself, but that feels like the correct way to do it.

**Comment by pieryvdl** [comment]
I see the build failed. It may be just that the version is outdated. You could try "flutter pub get" and "flutter pub upgrade" on the branch.

**Review by MonikaTheiss — APPROVED** [review]

**Comment by MonikaTheiss** [comment]
Build failed in the get dependencies part, because there were 2 http versions in the pubspec file

**Comment by MonikaTheiss** [comment]
@pieryvdl please approve it again, I can't approve because I changed the files

**Review by pieryvdl — APPROVED** [review]
Codewise looks good.

**Pull request merged**
