### PR TITLE
Feat/game library

### PR DESCRIPTION
**Pull request by u22520016**

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
Code looks good!

**Review by MonikaTheiss — APPROVED** [review]
Code looks good, we just need a way to get to the game library from the home page

**Comment by MonikaTheiss** [comment]
@pieryvdl  do we merge this or wait for the routing to be added before merging?

**Comment by pieryvdl** [comment]
@MonikaTheiss We should just ask Franco if he is busy on the branch with the routing. If he is not we can, merge it in, otherwise we should wait for him first. Ideal would be to add the routing first and then merge to Dev, but otherwise it should be fine just merging this in now and fixing routing later.

**Comment by pieryvdl** [comment]
@u22520016 Please see the comments above.

**Comment by pieryvdl** [comment]
Franco let me know that he has not changed the routing, I'm merging this to Dev

**Pull request merged**
