### PR TITLE
Feat/see connections profile

### PR DESCRIPTION
**Pull request by LeratoKgomo**
you can now see other users profile page 
from the :

1. search page 
2. connections page of any other user 
3.  your own request page 

- if account is private and isn't your connection you wont see their games ( you can test this buy putting a user with a visibility field of false in the requests array )
- but if you are connected you should see the profile regardless(test this by moving the user above to the connections array)

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
WhatsApp Image 2024-08-01 at 22 14 07_44b345dc
WhatsApp Image 2024-08-01 at 22 14 06_5a2dd02c

I ran your branch on my side. There are just 2 small things I saw , When you go onto another account's profile and check their connections, you can select the disconnect button, which then disconnects your profile from that selected connection. I am worried that if we click on disconnect from a profile we are not connected to , it might give problems. Then another small thing I saw was on the bytesquad profile, because it didnt have any game data, it looks like I am able to give them games 😅

**Comment by LeratoKgomo** [comment]
> WhatsApp Image 2024-08-01 at 22 14 07_44b345dc WhatsApp Image 2024-08-01 at 22 14 06_5a2dd02c
> 
> I ran your branch on my side. There are just 2 small things I saw , When you go onto another account's profile and check their connections, you can select the disconnect button, which then disconnects your profile from that selected connection. I am worried that if we click on disconnect from a profile we are not connected to , it might give problems. Then another small thing I saw was on the bytesquad profile, because it didnt have any game data, it looks like I am able to give them games 😅

i managed to fix these please let me know if theres any other issues

**Comment by MonikaTheiss** [comment]
@LeratoKgomo I can't see the games on my profile anymore ... even though I do have games on firebase?

**Comment by LeratoKgomo** [comment]
> @LeratoKgomo I can't see the games on my profile anymore ... even though I do have games on firebase?

this should be fixed now

**Review by MonikaTheiss — APPROVED** [review]
Looks good, I'm happy , thank you !

**Review by pieryvdl — APPROVED** [review]
Changes look good! Thank you Lerato!

**Pull request closed without merging**
