### PR TITLE
Fix/feed page timer fix

### PR DESCRIPTION
**Pull request by u22520016**
I fixed the timer issues (not changing time when switching pages and not recording the time in the stats page) by adding a service that acts as a global way to keep track of the time, even if the widget reloads...

By the way...this made me realize that we do not separate all logic in the view into services, which we should (since we can implement easy caching and data sharing and global data in this manner)

Please check if it works on your side.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Hi @u22520016 thank you it works great! It does seem like the mood thingys don't work as it should anymore, the chosen mood doesn't change color when you select it anymore

**Comment by shan-226** [comment]
It works! But I also have same problem with the mood ratings not showing when you click it anymore.

**Comment by u22520016** [comment]
Okay I fixed the mood animation issue

**Review by MonikaTheiss — APPROVED** [review]
Yep it works again, thank you!

**Review by shan-226 — APPROVED** [review]

**Pull request merged**
