### PR TITLE
added accept and reject functionality

### PR DESCRIPTION
**Pull request by LeratoKgomo**
- should be ab le to now accept and reject a request 
- just let me know of your users ill add 2 friends for you , you can accept one and reject the other

### CODE REVIEW

**Comment by pieryvdl** [comment]
rsYgmKH4bOUmhTFcTyKepTcX2Of2 Hi @LeratoKgomo Could you add 2 friends requests for me, that is my UID

**Comment by LeratoKgomo** [comment]
@pieryvdl all set let me know if theres issues

**Comment by MonikaTheiss** [comment]
oD6vFzqP14MmNNyfWtxPnZVtZQQ2 Me too please 😊

**Review by pieryvdl — APPROVED** [review]
Works perfectly. Thank you Lerato!

**Comment by LeratoKgomo** [comment]
@MonikaTheiss all set you can try now

**Review by MonikaTheiss — APPROVED** [review]
I'm also happy ! Thats great , we just need to remember for tomorrow not to have too many connections, because I see we cant scroll through the friends on the profile page

**Pull request merged**
