### PR TITLE
Fix/view specific event bug

### PR DESCRIPTION
**Pull request by MonikaTheiss**
When you dont have any joined events, the tab bar view is much bigger (takes up more space). I have also worked on the subscribe functionality. The functionality now works, when you subscribe to an event and go to the subscribed events tab, you should now see the event there . Unsubscribing does also work, although there is a little bug in the way it displays. and I don't know yet why this is happening, however it does unsubscribe you and when you switch to all events and back to subscribed , it does indeed remove that event from your subscribed. I think this is good enough for the usability testing for now. I will obviously have to work on the displaying some day.

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
Code works as intended. Thanks Monika!

**Comment by shan-226** [comment]
On the view events page, when you do not have any upcoming events, the other events do expand but they don't take up the entire length of the screen. There is a white space beneath it and then you scroll in a box/container. Would it be possible to edit this so that it either takes up the entire length of the screen and then scrolls in that box or just allow the user to scroll the entire page to see more events and not inside the box. (I hope that made sense)
I also found a small bug: You can't un-join an event.

But everything else looks good and works as intended.

**Comment by MonikaTheiss** [comment]
I have thought about this yesterday evening, and I will undo that change I made to the size of the other events, will just add text to say user has not joined any events yet. I feel that will make more sense

**Review by shan-226 — APPROVED** [review]
It works.

**Pull request merged**
