### PR TITLE
Feat/displayfriendsinprofile into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
I split up some of the code to make it more modular. Then I also added functions to fetch the friends in the friends database and display all of your friends in your profile. It is not perfect yet but I would like to move on to other things until the UI is sorted.

### CODE REVIEW

**Comment by pieryvdl** [comment]
So the hosting is going to fail for now because the files are not in main. They need to have a build/web/index.html file, which is currently in the gitignore. We can maybe adjust it later to ensure that the hosting works properly.

**Comment by pieryvdl** [comment]
I changed the new workflow to only deploy on pushes to main.

**Comment by pieryvdl** [comment]
@MonikaTheiss @LeratoKgomo Please let me know if you guys are happy with the progress so far. :)

**Review by MonikaTheiss — APPROVED** [review]
Looks good! Thank you 😄

**Comment by LeratoKgomo** [comment]
looks great

**Review by LeratoKgomo — APPROVED** [review]

**Pull request merged**
