### PR TITLE
Fix/usability fixes2 into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Hi guys, so this is round 2 of the usability fixes:

1. Added padding to left-hand side of input box on Chatpage
2. Moved the Theme component into 'Appearance'
3. I added "description" on specific game page and moved the content around a bit, please let me know what you think about the structure of this page or if you are happy with it. 
4. I styled the "No connection request" under the requests on the connection requests
5. Renamed everything Feed to 'Home'
6. Fixed the alignment of the emojis on Activity page
7. Added a condition to prevent you from seeing connections of private profiles (you can test this by checking out a private profile and checking their connections spoiler: you can't ;) 
8. I fixed the caching of the images on the message page (the page still loads slowly, 2 seconds faster than previously before the fix)
9. Fixed the images on message page from reloading when scrolling down and up again (also fixed setState error here) 

Please let me know about the fixes! Thanks in advance.

### CODE REVIEW

**Comment by pieryvdl** [comment]
Also I realised that there is conflicting files on this branch but the Resolve conflicts button is not possible to click? Can't remember how we fixed that last time? Any advice on that appreciated.

**Comment by MonikaTheiss** [comment]
> Also I realised that there is conflicting files on this branch but the Resolve conflicts button is not possible to click? Can't remember how we fixed that last time? Any advice on that appreciated. i have a feeling that I will have to pull Develop into my branch? I also believe that it might be the renaming of Feedpage that is causing the most issues, so I might have to revert that commit.

I don't know if you saw but you need to resolve the commits in terminal,below the "This branch has conflicts that must be resolved" heading, it says use the command line, you can click on that text and it will give you instructions on how to do that. Bt maybe see if pulling Dev into your branch could fix it.

**Comment by pieryvdl** [comment]
Hey guys,  I fixed the merge and fix 10. I changed the colors to primary of the back button on the specific game page. You cna now review the pull request, please. 😄

**Comment by MonikaTheiss** [comment]
From running it on my side the only thing I would want to change is remove the Theme heading in customize page. WIll look at the code now

**Review by MonikaTheiss — APPROVED** [review]
Code looks good! Thank you for covering so many things for us!

**Comment by pieryvdl** [comment]
> From running it on my side the only thing I would want to change is remove the Theme heading in customize page. WIll look at the code now

Hi monika, I removed that part, it was originally removed, but I think it slipped back when I merged the conflicts, thank you for helping me pick that up.

**Review by u22520016 — APPROVED** [review]
The changes look very good, thank you

**Pull request merged**
