### PR TITLE
Fix/username

### PR DESCRIPTION
**Pull request by pieryvdl**
3 things that changed in this update:

1. the readme is the biggest change
2. I fixed the username bug that prevented a new user from changing their username (to test, make a new account via google)
3. Updated the code in main.dart to cycle randomly between API  keys to better manage our resources.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Code looks good ! I will just test everything tomorrow to see how it all works 😄 
One thing on the readme, would it perhaps be possible to somewhere just add our group email please? Everything else looks great,thank you!

**Comment by pieryvdl** [comment]
Cool. Will add it! Thanks Monika!

**Comment by pieryvdl** [comment]
@MonikaTheiss Added the content to the table at the bottom. 😄

**Comment by MonikaTheiss** [comment]
perfect, thank you !
I just ran it all on my side. It works , thank you! Just waiting for actions to pass 👍

**Review by MonikaTheiss — APPROVED** [review]
Thank you for this !

**Review by shan-226 — APPROVED** [review]

**Pull request merged**
