### PR TITLE
Feat/search connections design

### PR DESCRIPTION
**Pull request by LeratoKgomo**
updated the search connections page design as discussed

### CODE REVIEW

**Review by u22520016 — CHANGES_REQUESTED** [review]
I see that the disconnect is a very slight different shade of green than the primary colour.  I would rather make it a much lighter green, almost like the light-mode chat bubble colour on Figma.  You could possibly use the tertiary colour in the themes for this.  I also noticed that the Disconnect button is ever so slightly off-center and to the left.  I do not know if my eyes deceive me or if it can be fixed, but please have a look at these things

**Comment by u22520016** [comment]
> I see that the disconnect is a very slight different shade of green than the primary colour. I would rather make it a much lighter green, almost like the light-mode chat bubble colour on Figma. You could possibly use the tertiary colour in the themes for this. I also noticed that the Disconnect button is ever so slightly off-center and to the left. I do not know if my eyes deceive me or if it can be fixed, but please have a look at these things

Actually, it looks like all text in the buttons are off-center to the left

**Review by pieryvdl — CHANGES_REQUESTED** [review]
Hi Lerato, I agree with Franco, the colors for the connect and disconnect look very similar. If we could get more contrasts in those greens it would be great. Also to me the text does look correctly aligned, but maybe you can ty something like: textAlign: TextAlign.center, inside the Text components? But the rest of the page looks good, thank you!

**Comment by LeratoKgomo** [comment]
> I see that the disconnect is a very slight different shade of green than the primary colour. I would rather make it a much lighter green, almost like the light-mode chat bubble colour on Figma. You could possibly use the tertiary colour in the themes for this. I also noticed that the Disconnect button is ever so slightly off-center and to the left. I do not know if my eyes deceive me or if it can be fixed, but please have a look at these things

-for the disconnect button i used the tertiary colour 
- on my side they all centered can you maybe send me a screenshot from your side?

**Review by u22520016 — APPROVED** [review]
Looks good.  I will change the colors

**Review by pieryvdl — APPROVED** [review]
Franco will change the colors, thank you Lerato!

**Pull request merged**
