### PR TITLE
feat/loginBugFix2

### PR DESCRIPTION
**Pull request by pieryvdl**
fixed bug with checking if profile exists. Should now work properly.

### CODE REVIEW

**Review by MonikaTheiss — APPROVED** [review]
Thank you! It works, the only thing we have to look at later on is the unique num not updating. But this is already a big step into the right direction.

**Comment by MonikaTheiss** [comment]
I believe I fixed the unique num issue on my update default profile branch. The problem was we were using the services file for google sign in but not for the normal signin, so we got confused and never called getNextNum when loggin in with google. Will soon create a pull request for my fixes and then it should be fixed

**Comment by pieryvdl** [comment]
> I believe I fixed the unique num issue on my update default profile branch. The problem was we were using the services file for google sign in but not for the normal signin, so we got confused and never called getNextNum when loggin in with google. Will soon create a pull request for my fixes and then it should be fixed

Thank you Monika, just waiting for @LeratoKgomo to approve and then I will merge this in.

**Comment by pieryvdl** [comment]
I also resolved the merge conflicts and should be able to merge when approved.

**Comment by LeratoKgomo** [comment]
what exactly should i test? 
did you fix the problem we had with making a new profile each time you login with google?

**Comment by pieryvdl** [comment]
Yes exactly that issue. 😅

**Comment by LeratoKgomo** [comment]
works well, thank you

**Review by LeratoKgomo — APPROVED** [review]

**Pull request merged**
