### PR TITLE
Feat/create event

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Users can now invite connections by clicking on the "invite connections to join" button. This will take them to a list of all their connections. They can then select the connections they want to invite. They then click on "Save invites" to save it and navigate back to the create event page. If they click on "create", the event will be created with all the connections they have invited. I assumed if they were invited, that means they are subscribed to the event, so the uid's will be stored in the subscribed variable in the database. This is not final, and I have not yet added a way for user feedback, I wanted to get the invites done first because that's a big thing to do , which takes a lot of time.

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Please also check that the search connections page, the connections list and the connection request page still function normally, since I did have to change quite a few things on those pages , since I used the user model for my invites. Basically anything that uses the connections should be checked. I have tested everything , but it might be that I missed something, so please just double check.

**Comment by LeratoKgomo** [comment]
looks great. I got a bit confused without the feedback i created a few events by mistake so i agree we will need that . The images load pretty quickly as well ,thats great! functionality works as it should but only if the user has connections so if they dont have it gives an error , Im not sure how we going to handle that case.  I also have a few suggestions on the design :

- can you move the back icon to the far left 
-maybe also heading in bold without the colon 
- maybe have the save invites as a button or for now the way it is without the plus icon since in the previous page you already use the icon

**Comment by pieryvdl** [comment]
I ran the branch now, there seems to be an error in the functions, but I'm pretty sure it could just be my profile. 
image
Upon further inspection it seems the error is form the getConnectionsForInvite() function. It could be by extension this function getConnections(String who) I can look into it properly tommorrow, but just thought I'd let you know in the mean time.

**Comment by MonikaTheiss** [comment]
So I havee tested what happens when the user does not have any connections, and this is not a issue, as it just is an empty page , it doesnt give an error. 

@pieryvdl  you are getting that error I believe because you have a connection which does not have a profile data its uid 6VCYkgR8o7PjKPaMLnRj6KPdQZ63. If you remove this profile from your connections list, it should work. Let me know if it does?

@LeratoKgomo I will make those updates quickly, thank you ! Just a question about the error you mentioned, do you mean when the user does not have a connection document or when they dont have any connections in their connection document?

**Comment by LeratoKgomo** [comment]
i believe its when there isn't at least 1 connection in the connections array. I got the same error as piery.

**Comment by MonikaTheiss** [comment]
> i believe its when there isn't at least 1 connection in the connections array. I got the same error as piery.

Okay, I did test it on my side with no connections and it did still work, it just gave an empty invite page. Which account are you using? I suspect you might also have a connection that does not have a profile data document?

**Comment by LeratoKgomo** [comment]
wait Im actually not sure what could be the problem because i just checked all my connections data and they seem to have the necessary data that you display on that page

**Review by LeratoKgomo — APPROVED** [review]
works perfectly now , thank you for adding my suggestions everything looks great

**Comment by pieryvdl** [comment]
Hi, it seems the faulty connection was the issue it works perfectly now, thank you @MonikaTheiss

**Review by pieryvdl — APPROVED** [review]
The changes applied work. I like the user feedback via the snackbar. The event is also added correctly to firebase.

**Review by pieryvdl — APPROVED** [review]
Code looks good. In the future we should just add code to clear the event after it has been created.

**Pull request merged**
