### PR TITLE
Feat/game library

### PR DESCRIPTION
**Pull request by u22520016**
New changes

### CODE REVIEW

**Comment by pieryvdl** [comment]
Code looks good on the branch. Just waiting for the merge conflicts to be resolved, then I will approve after running. But the work looks excellent thanks Franco!

**Comment by u22520016** [comment]
Merge conflicts are resolved and I also fixed the actions failing.

**Review by pieryvdl — APPROVED** [review]
Okay code wise it looks good. Although I think some of the merge conflicts might have taken away the ability to view the specific game page. @MonikaTheiss we just need to connect it back?

**Review by MonikaTheiss — APPROVED** [review]
Looks good, thank you

**Pull request merged**
