### PR TITLE
Feat/make create events pretty

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Worked on making the create events page "pretty" The required fields are now higlighted in red. I also provided a little bit of user feedback when selecting a game an connections for invites. I also check the end date and time and dont allow the user to create the event until it is the correct date and time. Please let me know if I missed something

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
@pieryvdl I couldn't figure out how to navigate the user to a different page without losing the navbar and app bar completely, so I settled on just clearing everything for now.

**Review by pieryvdl — CHANGES_REQUESTED** [review]
image
I couldn't select a game to play and got an error in the terminal. Might be a minor error, could you please check it out. :)  I really love the red though. It looks great and I think it is what the user needed. COuldn't create the event and correctly got the snackbar message.

**Comment by MonikaTheiss** [comment]
ah I see i have conflicts now as well. 
@pieryvdl I will look at it, however I did find that RAWG gave some issues on retrieving the games at a stage, and I also found the problem on the profile page. Will look into it though

**Comment by MonikaTheiss** [comment]
Franco's changes broke my stuff a bit. Will reopen when I have addressed all issues

**Comment by MonikaTheiss** [comment]
I think I fixed everything. I have now also noticed a little inconsistency in where I load the data between the choose games and invite pages. But the only difference is the loading of pages.

**Comment by LeratoKgomo** [comment]
looks great i also like the read borders can you , i noticed though you didnt do the same for the description was it a mistake ?  
The spacing is great i would also suggest adding spacing for the rest of the page (everything under the game session and tournament buttons).  
Im also having the same problem piery had.
I also noticed the color change when invites are selected  thank you for that. 
The search bar is a great idea to make it easier for the user , just a minor suggestion  maybe move the search bar to start at the same point as the images.
Other than that it looks great thank you ...since the suggestions are minor ill wait for your response on the other stuff then approve

**Comment by MonikaTheiss** [comment]
> looks great i also like the read borders can you , i noticed though you didnt do the same for the description was it a mistake ? The spacing is great i would also suggest adding spacing for the rest of the page (everything under the game session and tournament buttons). Im also having the same problem piery had. I also noticed the color change when invites are selected thank you for that. The search bar is a great idea to make it easier for the user , just a minor suggestion maybe move the search bar to start at the same point as the images. Other than that it looks great thank you ...since the suggestions are minor ill wait for your response on the other stuff then approve

Description is not red as it is not a required field the creator has to fill in. I made the required fields red, and the fields that are not required green. You'll see when you add the correct input in the red fields, they will turn green.

I don't know why you are still getting that error , could you perhaps send me a screenshot of the console?

Currently I'm not too worried about making everything look perfect , as I am aware we will probably change a few things next week, so I don't want to change too many things about the design right now, in case we decide to redo it all.

**Comment by MonikaTheiss** [comment]
@LeratoKgomo are you sure you are running the most recent code? I just tried running it on your account and it worked fine on my side. I did however see a smallish bug where it repeats the games every time you go out and go in again.. but that does not give an error

**Review by pieryvdl — APPROVED** [review]
Code now works on my side as of testing this morning. I created a new event, checked the time and added a game successfully.  Had a small typo on the event name, but I think that is a user (me) error 😆 . Thanks Monika, great work!

**Review by pieryvdl — APPROVED** [review]

**Comment by LeratoKgomo** [comment]
Oh i see what you mean with the description ,
well it now works hey

**Review by LeratoKgomo — APPROVED** [review]

**Review by pieryvdl — APPROVED** [review]

**Review by LeratoKgomo — APPROVED** [review]

**Pull request merged**
