### PR TITLE
Fix/messagesnotloading into Develop

### PR DESCRIPTION
**Pull request by pieryvdl**
Hey guys, 

1. fixed the messaging page not loading
2. when a user makes an empty chat with someone the primary text will now display that there were no messages found

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Seems to work on my side , only issue I saw was the phone back button does not seem to work on the messaging page. Don't think this is something we could fix, I also had issues with my keyboard, might just be my phone. Will look at code now.

**Review by MonikaTheiss — APPROVED** [review]
Looks good , thank you for fixing this !

**Comment by shan-226** [comment]
The message page unfortunately does not load on my side. Is this because I am running it on web or should it also work on web?

**Comment by pieryvdl** [comment]
Hi @shan-226 yes the messages have not been working on the web version for a while. I intend on fixing it at some point, just focused on getting the minigames and more pressing bugs fixed first.

**Review by shan-226 — APPROVED** [review]

**Pull request merged**
