### PR TITLE
Fix/automatically update event details

### PR DESCRIPTION
**Pull request by MonikaTheiss**
When editing an event, the updated information should now be displayed immediately when information is saved. I also changed the scrolling on the invite connections page to work like the select game page

### CODE REVIEW

**Comment by LeratoKgomo** [comment]
looks great it updates automatically at the top on the joined events list  but not on the view page under the my events (but i guess its because the page doesnt reload?) so when you try to edit the event again it still gives the old data as though you havent edited it yet

**Review by pieryvdl — COMMENTED** [review]
Hi, I see Lerato left a comment. Is it possible to pull Develop into this branch? Or possibly switch reviewers? I'm struggling a bit with running the code. But I reviewed each line carefully, the code seems good.

**Comment by MonikaTheiss** [comment]
> Hi, I see Lerato left a comment. Is it possible to pull Develop into this branch? Or possibly switch reviewers? I'm struggling a bit with running the code. But I reviewed each line carefully, the code seems good.

Pulled Dev into this branch 👍

**Comment by pieryvdl** [comment]
@MonikaTheiss Thank you for pulling in Dev! I saw what @LeratoKgomo found. But I think this issue is miniscule to notice. Thank you for your hard work on the events. It is duly noted.

**Review by pieryvdl — APPROVED** [review]

**Comment by MonikaTheiss** [comment]
> looks great it updates automatically at the top on the joined events list but not on the view page under the my events (but i guess its because the page doesnt reload?) so when you try to edit the event again it still gives the old data as though you havent edited it yet

Hi @LeratoKgomo yeah I see the issue on my side too. It does upload when you switch to another tab and back,I think its the stream not updating when we move back to the view events page until we do something on the view events page. I am nnot sure how to fix it though, i fyou have any suggestions that would be of great help.

**Review by LeratoKgomo — APPROVED** [review]

**Pull request merged**
