### PR TITLE
see events

### PR DESCRIPTION
**Pull request by MonikaTheiss**
User can now view their subscribed events, their created events and their joined events

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
to see subscribed events, add your uid to an event's subscribed array. To see your joined events, add  your uid to the participants array of an event

**Review by LeratoKgomo — APPROVED** [review]
the UI for the events page looks really good honestly  , the functionality works as it should as well. Thank you for your effort on this page.

**Comment by pieryvdl** [comment]
image
When I opened the app I went to the events page and saw the subscribed events, but when I went and created an event and tried to view the event I got this error. Not sure if it was just my profile or a code error. Upon further inspection the function broke at the fetchAllEvents() in the event_service.dart . Hope this helps, it could be that my internet connection was not well, I will rerun it tomorrow.

**Comment by MonikaTheiss** [comment]
> image When I opened the app I went to the events page and saw the subscribed events, but when I went and created an event and tried to view the event I got this error. Not sure if it was just my profile or a code error. Upon further inspection the function broke at the fetchAllEvents() in the event_service.dart . Hope this helps, it could be that my internet connection was not well, I will rerun it tomorrow.

Luckily this is an easy fix, you are getting this error, because you used the old create events stuff, which does not have a subscribed array. However the events page needs a subscribed array to show the subscribed page, so you should be able to fix it by just adding an empty subscription array to the event you created( and any other events that might not have the subscribed array). Let me know if that fixes it?

**Review by pieryvdl — APPROVED** [review]
I addded the subrcribed array like you pointed out and it worked. The code works as intended. Well done and thank you Monika!

**Pull request merged**
