### PR TITLE
Feat/start timer

### PR DESCRIPTION
**Pull request by u22520016**
I added the fields that @LeratoKgomo and @shan-226 requested.  Please check if this is fine when creating a timed game session.  I also changed the emotions to Angry, Scared, Disgusted, Happy and Sad.  @MonikaTheiss please tell me what you think of this.

Steps to test:
1. Comment out the current body on the feed page
2. Add the GameTimer() component to the new feed page body
3. Test the app with a user that has games in their "My games"
4. Check the game_session_stats collection for updates.

### CODE REVIEW

**Review by MonikaTheiss — APPROVED** [review]
Looks great ! Thank you !!

We just need to remember to remove the old documents on the database that still have the old design, so Lerato and Shannon don't get errors because of it.

**Comment by LeratoKgomo** [comment]
looks good and works well But im not sure how your save the time spent to play the game but i need it in hours for the profile page thats the only problem from my side everything else looks good

**Comment by u22520016** [comment]
> Looks great ! Thank you !!
> 
> We just need to remember to remove the old documents on the database that still have the old design, so Lerato and Shannon don't get errors because of it.

Okay I will do that.

**Comment by u22520016** [comment]
> looks good and works well But im not sure how your save the time spent to play the game but i need it in hours for the profile page thats the only problem from my side everything else looks good

You can just use a time format function to get the hours, minutes and seconds spent playing the game.  To get the hours you just divide by 3600.  I just need to make sure that I stored seconds, rather than milliseconds.

**Pull request merged**
