### PR TITLE
Added snackbar for add to currently playing and add to wishlist

### PR DESCRIPTION
**Pull request by MonikaTheiss**

### CODE REVIEW

**Review by pieryvdl — APPROVED** [review]
Works perfectly. Thanks Monika!

**Comment by MonikaTheiss** [comment]
@LeratoKgomo could you please review this for me? So I can merge into Develop and then we can get Develop into main 😊

**Comment by LeratoKgomo** [comment]
can you explain what i should be testing

**Comment by MonikaTheiss** [comment]
the add to currently playing button and add to wishlist button on specific game page - I simply added a snackbar to pop up to say it was added to wishlist/currently playing

**Review by LeratoKgomo — APPROVED** [review]
looks great and it works , thank you

**Pull request merged**
