### PR TITLE
colors changed

### PR DESCRIPTION
**Pull request by MonikaTheiss**
Chnaged the colors used on GameOnConnect to follow the theme's colors as it was designed. The whole app should now use the darker green. Please let me know if I missed something. @pieryvdl and @u22520016

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
I will have a look at those over the weekend if I get bored, because I wasn't too sure how it would look, since we didn't design those 2 pages.

**Review by pieryvdl — APPROVED** [review]
Works as intended.

**Comment by MonikaTheiss** [comment]
@u22520016 please review this when you get the time .

**Review by u22520016 — APPROVED** [review]
Looks good

**Pull request merged**
