### PR TITLE
Feat/profile page

### PR DESCRIPTION
**Pull request by LeratoKgomo**

### CODE REVIEW

**Comment by LeratoKgomo** [comment]
@pieryvdl  May you please review

**Review by pieryvdl — DISMISSED** [review]
COde wise looks good. I couldn't run it because I have run out of Disk space, will sort it out. I am approving, will just let someone else run it before we merge it in. Thank you Lerato!

**Comment by MonikaTheiss** [comment]
@LeratoKgomo I am busy trying to run it , I ran into some issues that I'm trying to fix. When I fix those, I will be able to review the profile page.

**Comment by MonikaTheiss** [comment]
I finally found the profile page. @LeratoKgomo if you have a look at Shannon's page , she created a button on the main page that links to the edit profile page. Could you please add a button like that to the home page that links to your profile page? This way we won't have to change the main.dart to see the profile. Thank you for the hard work you have put into the profile page !

**Comment by MonikaTheiss** [comment]
Looks much better ! Thank you @LeratoKgomo !! Let @pieryvdl just have a look at your code and if he is happy with everything then you can merge. Just give him a bit of time to get to it

**Review by pieryvdl — APPROVED** [review]
Aprroving these changes, you can merge into main. Thanks Lerato!

**Comment by pieryvdl** [comment]
Don't worry about the tests for now, we will sort those out today.

**Pull request merged**
