### PR TITLE
Feat/game activity

### PR DESCRIPTION
**Pull request by LeratoKgomo**
should be able to see the activities for my games if there are any ... and also now the see more  button works

### CODE REVIEW

**Comment by MonikaTheiss** [comment]
Oh wow that looks great !!! Thank you @LeratoKgomo ! I will quickly have a look at the code and leave a review ☺️

**Comment by shan-226** [comment]
It looks so good! I absolutely love it!
It seems to be working but I found a small bug. I started a playing session to test out the live playing now feature on the profile and after I ended the session that data was not updated and added to my recently playing list. I closed and restarted the app to see if it was just that it didn't update in real time but that was not the case. That recently played game was not updated on the profile at all. I couldn't find that playing session in the gaming_session_stats table on firebase so I think the problem may be on @u22520016 's side.

**Review by MonikaTheiss — COMMENTED** [review]
Looks great ! Thank you! Please  address @shan-226 's point

**Comment by MonikaTheiss** [comment]
> It looks so good! I absolutely love it! It seems to be working but I found a small bug. I started a playing session to test out the live playing now feature on the profile and after I ended the session that data was not updated and added to my recently playing list. I closed and restarted the app to see if it was just that it didn't update in real time but that was not the case. That recently played game was not updated on the profile at all. I couldn't find that playing session in the gaming_session_stats table on firebase so I think the problem may be on @u22520016 's side.

I have tested this out on my side and it seems to be working for me. The game info is updated correctly and displays.

**Review by MonikaTheiss — APPROVED** [review]

**Comment by LeratoKgomo** [comment]
> It looks so good! I absolutely love it! It seems to be working but I found a small bug. I started a playing session to test out the live playing now feature on the profile and after I ended the session that data was not updated and added to my recently playing list. I closed and restarted the app to see if it was just that it didn't update in real time but that was not the case. That recently played game was not updated on the profile at all. I couldn't find that playing session in the gaming_session_stats table on firebase so I think the problem may be on @u22520016 's side.

yes @u22520016 is supposed to add the game after the session to the currently playing field (currently its done manually ) ... as for not finding the document maybe @u22520016 might know something about that , if the document isnt there you wont be able to see it on your profile either

**Review by shan-226 — APPROVED** [review]
Okay cool. Since the problem isn't on you side I approve. It looks really good, thank you.

**Comment by MonikaTheiss** [comment]
> Okay cool. Since the problem isn't on you side I approve. It looks really good, thank you.

maybe add this bug as an issue on github, just so we dont forget about it please.

**Pull request merged**
